import { hotel } from './index.js';
console.log(hotel.getLength());
console.log(hotel.getActualFreePlace());
console.log(hotel.paidPerPlace());
console.log(hotel.guests);
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.checkInGuest('Nastya', 'Pliuta', 30));
console.log(hotel.getLength());
console.log(hotel.getActualFreePlace());
console.log(hotel.paidPerPlace());
console.log(hotel.guests);
